version: '3.8'
services:

  # PBX / Asterisk — для приёма/отправки звонков
  asterisk:
    image: mlan/asterisk:full
    container_name: ai-call-center-asterisk
    ports:
      - "5060:5060/udp"
      - "10000-10099:10000-10099/udp"
    volumes:
      - ./asterisk-config:/etc/asterisk
    networks:
      - callnet

  # PostgreSQL — хранение логов и аналитики
  postgres:
    image: postgres:15
    container_name: ai-call-center-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: calluser
      POSTGRES_PASSWORD: callpass
      POSTGRES_DB: callcenter
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - callnet

  # Whisper-local ASR
  whisper-asr:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: ai-call-center-whisper
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - callnet

  # Rasa NLU
  rasa:
    image: rasa/rasa:3.6.2-full
    container_name: ai-call-center-rasa
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./assistants/rasa:/app
    ports:
      - "5005:5005"
    networks:
      - callnet

  # Rasa Actions Server
  rasa-actions:
    image: rasa/rasa-sdk:3.6.2
    container_name: ai-call-center-rasa-actions
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./assistants/rasa:/app
    ports:
      - "5055:5055"
    networks:
      - callnet

  # Silero TTS (через coqui-ai/tts образ)
  tts:
    image: coqui/tts:latest
    container_name: ai-call-center-tts
    restart: unless-stopped
    ports:
      - "6000:6000"
    networks:
      - callnet

volumes:
  pgdata:

networks:
  callnet:
    driver: bridge
